### ISSUE TITLE
Reduce search time cost

### ISSUE THREAD

**Issue by dongli** [dongli/fortran-octree#1]
Thanks to Joe Todd's [suggestion](https://www.researchgate.net/messages/990765909)! When testing 10k points, the cost is reduced by 50 times!

**Comment by dongli** [comment]
Fixed in [71cdd3](https://github.com/dongli/fortran-octree/commit/71cdd30215c41b7dd15088cc9a174b35de06716f).

**Comment by joeatodd** [comment]
Glad it helped :)
